### ISSUE TITLE
Documentação Geral

### ISSUE THREAD

**Issue by MTruffi** [unico-mvg/unico-sdkbio-docs#10]
Alterações na documentação
**Introdução**
- [x] O que oferecemos - Corrigir nomenclatura 1:1 agora é chamado de Token biométrico
- [x] Incluir a SDK como serviço, afirmando os benefícios de segurança. Tem mais informações nas alterações do FAQ no final deste issue

**Primeiros passos/Começando**

- [x] SDKs disponíveis - link não deveria ir para o download da SDK? se não está parte poderia ser a "Estrutura dos guias"

- [x] Funcionalidades disponíveis por SDK - O que são customizações avançadas? Na SDK web temos customizações de cores como nas outras: https://www3.acesso.io/sdkbio/implementation.html?type=npm&n=2 parte de Layout

**Conceitos importantes**

- [x] Incluir bullets: 
- A funcionalidade de liveness com interação depende de contato com o nosso backend
- Não damos suporte para versões desatualizadas das nossas SDKs.

**FAQ**

- [x] Incluir após a pergunta: "Qual é o diferencial da nossa SDK?​"

1. Quais as camadas de segurança das SDKs unico? 
_Nossas SDKs possuem diversas camadas de segurança que funcionam de forma complementar, tanto a nivel da aplicação quanto em relação aos dados que trafegados entre as SDKs e nosso backend. Nossa SDK possui ofuscação de código, bloqueio de emulador e checagem de bundle do aplicativo que a está executando._ 

3. Qual a rigidez da segurança do JWT? Qual o nível de criptografia? 
_Os arquivos trafegam em um canal seguro usando criptografia TLS.
Cada arquivo também é criptografado usando o formato JWS (Json Web Signature), que contém as informações da criptografia, os dados que queremos enviar e uma assinatura para o token gerado. 
A principal ferramenta de segurança do JWS é a assinatura, que é invalidada caso o conteúdo seja alterado. 
Além disso, os prazos de expiração dos tokens são curtos, então a janela para qualquer ataque é pequena._

4. Qual é o tamanho do payload do JWT?
_O JWT gerado pelas nossas SDKs tem em média 300kb._

- [x] Incluir parte de customizações para versão iOS e Android

**Comment by mrcsvg** [comment]
@MTruffi , entendidos os issues. Vou trabalhar neles.

**Comment by MTruffi** [comment]
@mrcsvg Detalhando a parte de customizações, tem 2 pontos que podemos ajustar ainda:

**Comment by mrcsvg** [comment]
> @mrcsvg Detalhando a parte de customizações, tem 2 pontos que podemos ajustar ainda:
> 
> * [ ]  A forma como está no guia web fica melhor, com as alterações de layout no fluxo de implementação.

Não entendi esse item, @MTruffi

**Comment by MTruffi** [comment]
Sobre esse item me refiro a forma como ficou organizado as customizações do frame no guia de implementação da SDK web:

![image](https://user-images.githubusercontent.com/98483498/157668121-f2faa1b8-0979-4678-804c-5071bd3035f9.png)
