### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by MTruffi** [unico-mvg/unico-sdkbio-docs#18]
- [ ] Incluir o código do GA na documentação para acompanhamento e análise:

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-168684880-1%22%3E</script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-168684880-1');
</script>

**Comment by mrcsvg** [comment]
@MTruffi , qual versäo do analytics vc ta usando? Tem como passar o tracking id?

**Comment by mrcsvg** [comment]
Feito com G-5LCWFXWSWB
