### ISSUE TITLE
Documentação Android - Dúvidas

### ISSUE THREAD

**Issue by mrcsvg** [unico-mvg/unico-sdkbio-docs#2]
# Dúvidas documentação Android

- [x] Dúvida métodos genéricos
- [x] Obrigatoriedade dos métodos de retorno
- [x] Configurações de smart e manual cameras
- [x] Pacotes requeridos
- [x] Fallback camera normal
- [x] Json com as chaves vai ser necessário apenas para o Liveness ativo? (Facetech)? Ou para tudo?
- [x] Captura de documento também usa o json com as chaves?
- [x] Arquivo Json
- [x] Parâmetro encrypted

### Métodos Genéricos

> Existem dois métodos genéricos como onErrorAcessoBio e onUserClosedCameraManually. Veja a lista abaixo com a descrições:

Não entendi esse comentário... o que diferencia esses métodos? Qual a diferença deles para os outros? Como o  `onSystemClosedCameraTimeoutSession()`, por exemplo

### Obrigatoriedade dos métodos de retorno

Todos os métodos e retorno devem ser declarado? Se não declarar o que acontece? O SDK lança alguma exceção ? 

### Configurações para o modo manual

> Por padrão a câmera possui o enquadramento inteligente e a captura automática habilitados. Neste caso, para utilizar o modo manual ambas configuraçooes relacionadas a Smart Camera devem ser desligadas através dos métodos `setAutoCapture` e `setSmartFrame`.

Existe a possibilidade de desligar o setAutoCapture e não desligar o setSmartFrame? Neste caso o que acontece? 

O que acontece quando:

setAutoCapture = True e setSmartFrame = True > Smart Camera
setAutoCapture = False e setSmartFrame = False > Manual Camera
setAutoCapture = True e setSmartFrame = False  > ? 
setAutoCapture = False e setSmartFrame = True > ?

### Pacotes a importar

Posso considerar que os pacotes necessários são:

```
import com.acesso.acessobio_android.AcessoBioListener
import com.acesso.acessobio_android.iAcessoBioDocument
import com.acesso.acessobio_android.iAcessoBioSelfie
import com.acesso.acessobio_android.onboarding.AcessoBio
import com.acesso.acessobio_android.onboarding.IAcessoBioBuilder
import com.acesso.acessobio_android.onboarding.camera.UnicoCheckCameraOpener.Document
import com.acesso.acessobio_android.onboarding.camera.UnicoCheckCameraOpener.Selfie
import com.acesso.acessobio_android.onboarding.camera.document.DocumentCameraListener
import com.acesso.acessobio_android.onboarding.camera.selfie.SelfieCameraListener
import com.acesso.acessobio_android.onboarding.types.DocumentType
import com.acesso.acessobio_android.services.dto.ErrorBio
import com.acesso.acessobio_android.services.dto.ResultCamera
```

### Fallback para camera normal

No SDK Web existe um fallback para a camera normal caso a smart camera n funcione. Essa opção existe para Android tb?

>Alguns celulares antigos, como aparelhos com Android 6 ou iPhone 4, podem não possuir suporte aos recursos necessários para o funcionamento das técnologia de visão computacional, como face-api e tjfs, que são utilizadas em nossa funcionalidade de Câmera Inteligente. Nestes casos, a funcionalidade de Câmera Normal irá ser acionada como fallback, permitindo que o usuário faça a captura manual.

**Comment by henrique-cocito** [comment]
### Métodos Genéricos

Os métodos `onErrorAcessoBio`, `onUserClosedCameraManually`, `onSystemClosedCameraTimeoutSession` e `onSystemChangedTypeCameraTimeoutFaceInference` são métodos de callback. Sendo que:

- `onErrorAcessoBio` -> É retornado para o cliente quando algum erro acontece durante todo o processo de criação e captura;
- `onSystemChangedTypeCameraTimeoutFaceInference` -> É retornado para o cliente quando o usuário fecha a camera manualmente, cancelando a captura;
- `onSystemClosedCameraTimeoutSession` -> É retornado para o cliente quando a camera é fechada automaticamente pela SDK devido há um tempo de inatividade;
- `onSystemChangedTypeCameraTimeoutFaceInference` -> Quando o usuário não consegue realizar a captura utilizando a camera inteligente dentro de um tempo estipulado internamente pela SDK, a camera é alterada automaticamente para manual e é retornado para o cliente através desse método de callback informando que o tipo da camera foi alterado.

### Obrigatoriedade dos métodos de retorno

Sim. O callback é retornado para alguma classe que implemente a interface `AcessoBioListener`, ou seja, todos os métodos dessa interface devem existir na classe criada. Caso não exista a implementação de todos os métodos desse contrato, o projeto do cliente não compilará.

### Configurações para o modo manual
- **Smart Camera** - _Captura automática quando o rosto estiver enquadrado_
  `setAutoCapture` = `true`
  `setSmartFrame` = `true`

- **Manual Camera** - _Captura manual, sem identificação de enquadramento do rosto_
  `setAutoCapture` = `false`
  `setSmartFrame` = `false`
  
- **Manual Camera** - _Captura manual, com identificação de enquadramento do rosto para habilitar o botão_
  `setAutoCapture` = `false`
  `setSmartFrame` = `true`
  
- **A confirmar - Em testes**
  `setAutoCapture` = `true`
  `setSmartFrame` = `false`
  
### Pacotes a importar
Sim

### Fallback para camera normal
Sim, quando a smart camera não consegue identificar uma face dentro de um tempo especificado internamente dentro da SDK, automaticamente é alterado para a camera normal, e o método `onSystemChangedTypeCameraTimeoutFaceInference` da interface `AcessoBioListener` é chamado.

### JSON com as chaves vai ser necessário apenas para o Liveness Ativo?
Não. O JSON é uma camada de segurança da nossa SDK utilizando autenticação por arquivo, ou seja, para utilizar a SDK é obrigatório o uso do arquivo JSON.

###  JSON para captura de documento
Sim. O JSON é uma camada de segurança da nossa SDK utilizando autenticação por arquivo, ou seja, para utilizar a SDK é obrigatório o uso do arquivo JSON.

**Comment by mrcsvg** [comment]
Valeu, @henrique-cocito . Super claro!
