### ISSUE TITLE
Documentação Web - Comentários 

### ISSUE THREAD

**Issue by MTruffi** [unico-mvg/unico-sdkbio-docs#8]
- [x] https://unico-mvg.github.io/unico-sdkbio-docs/guias/web/fluxos/reconhecimento-facial/#inicializar-nosso-sdk ->Neste caso, path teria que ser com domain, é um requisito de modelos, então teria que ser:

`unicoCameraBuilder.setModelsPath("https://meusite.com.br/models");`

- [x] Atualizar Release notes: "Versão 2.0.3
- Correção em um bug nas implementações em Angular > 6. Este bug deixava a tela congelada quando houvesse concorrência entre setTimeout's em nosso SDK e a aplicação do cliente."

**Comment by mrcsvg** [comment]
Opa! A mesma coisa se aplica aos Resources?

```javascript
unicoCameraBuilder.setResourceDirectory("/resources");
```

**Comment by mrcsvg** [comment]
Quanto ao release notes:

Já temos uma versão 3.0, certo? Vcs já tem uma versão resumida do release notes?

**Comment by MTruffi** [comment]
> 

O time tem mantido os release notes atualizados na documentação antiga: https://www3.acesso.io/sdkbio/implementation.html?type=npm&n=2
