### ISSUE TITLE
Documentação Android - Ajustes identificados

### ISSUE THREAD

**Issue by MTruffi** [unico-mvg/unico-sdkbio-docs#9]
- [x] Seção: [Como começar | Unico Check - SDKs](https://unico-mvg.github.io/unico-sdkbio-docs/guias/android/como-comecar#embarcando-as-credenciais-em-seu-projeto) 

De: Selecione a opção JS

Para: Seleciona a opção Android

- [x] Seção:[Como começar | Unico Check - SDKs](https://unico-mvg.github.io/unico-sdkbio-docs/guias/android/como-comecar#precisando-de-ajuda) 

De: Entre em contato através de nosso e-mail [uporte.unicocheck@unico.io](mailto:uporte.unicocheck@unico.io);

Para: Entre em contato através de nosso e-mail [suporte.unicocheck@unico.io](mailto:suporte.unicocheck@unico.io);

- [x] Seção: [Captura de documentos | Unico Check - SDKs](https://unico-mvg.github.io/unico-sdkbio-docs/guias/android/fluxos/captura-documentos#inicializar-nosso-sdk) e [Reconhecimento facial | Unico Check - SDKs](https://unico-mvg.github.io/unico-sdkbio-docs/guias/android/fluxos/reconhecimento-facial#inicializar-nosso-sdk) 

De: public class MainActivity extends AppCompatActivity implements AcessoBioListener {

Para: public class MainActivity extends AppCompatActivity {

- [x] Seção: [Captura de documentos | Unico Check - SDKs](https://unico-mvg.github.io/unico-sdkbio-docs/guias/android/fluxos/captura-documentos#preparar-a-c%C3%A2mera-e-abrir-a-c%C3%A0mera) 

De: Preparar a câmera e abrir a càmera

Para: Preparar a câmera e abrir a câmera

- [x] Seção: [Captura de documentos | Unico Check - SDKs](https://unico-mvg.github.io/unico-sdkbio-docs/guias/android/fluxos/captura-documentos#efetuar-abertura-da-c%C3%A2mera) 

Antes de chamar o método prepareCamera, é preciso chamar o método build() na variável acessoBioBuilder... Isso retornará um objeto do tipo UnicoCheckCamera, essa interface sim contém o método prepareSelfieCamera e prepareDocumentCamera

- [x]  Atualização dos release notes
[4.0.5](https://github.com/acesso-io/acessobio-android/releases/tag/4.0.5) [Latest](https://github.com/acesso-io/acessobio-android/releases/latest)
[4.0.4](https://github.com/acesso-io/acessobio-android/releases/tag/4.0.4) error jitpack
 
4.0.4
Update GSON library to version 2.8.9
Open camera document in prepare camera

[4.0.3](https://github.com/acesso-io/acessobio-android/releases/tag/4.0.3)
Corrigimos um bug no modulo de abertura da câmera de documentos

[4.0.2](https://github.com/acesso-io/acessobio-android/releases/tag/4.0.2)
Corrigimos um bug que esteva deixando o debug lento ao utilizar nosso SDK.

[4.0.1](https://github.com/acesso-io/acessobio-android/releases/tag/4.0.1)
Corrigimos um bug no método prepare camera

**Comment by mrcsvg** [comment]
@MTruffi , sobre a atualização dos release notes: Vamos criar um conteúdo baseado nesses commits pra serem mais "user friendly". Isso vai manter a consistência com o que está lá. Exemplo: 

De
feat: Update Facetec to facetec-sdk-9.4.5-minimal.aar (solved the slowly debug problem)

Para:
Corrigimos um bug que esteva deixando o debug lento ao utilizar nosso SDK.
